CREATE EXTENSION IF NOT EXISTS vector;

CREATE TABLE IF NOT EXISTS "语义记忆" (
    "编号" BIGSERIAL PRIMARY KEY,
    "文本" TEXT NOT NULL,
    "来源" TEXT NOT NULL DEFAULT '',
    "向量" vector(384) NOT NULL,
    "全文" tsvector GENERATED ALWAYS AS (to_tsvector('simple', "文本")) STORED,
    "置信度" DOUBLE PRECISION NOT NULL DEFAULT 1.0,
    "过期时间" TIMESTAMPTZ,
    "创建时间" TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS "索引语义向量" ON "语义记忆" USING hnsw ("向量" vector_cosine_ops);
CREATE INDEX IF NOT EXISTS "索引语义全文" ON "语义记忆" USING gin ("全文");
CREATE INDEX IF NOT EXISTS "索引语义过期" ON "语义记忆" ("过期时间");

CREATE TABLE IF NOT EXISTS "情景记忆" (
    "会话号" TEXT PRIMARY KEY,
    "摘要" TEXT NOT NULL DEFAULT '',
    "轮数" INTEGER NOT NULL DEFAULT 0,
    "更新时间" TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS "跟踪跨度" (
    "跟踪号" TEXT NOT NULL,
    "跨度号" TEXT PRIMARY KEY,
    "服务" TEXT NOT NULL DEFAULT 'ai-service',
    "节点" TEXT NOT NULL,
    "状态" TEXT NOT NULL,
    "耗时毫秒" BIGINT NOT NULL DEFAULT 0,
    "输入快照" TEXT NOT NULL DEFAULT '{}',
    "输出快照" TEXT NOT NULL DEFAULT '{}',
    "错误" TEXT NOT NULL DEFAULT '',
    "创建时间" TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS "索引跟踪号" ON "跟踪跨度" ("跟踪号");

CREATE TABLE IF NOT EXISTS "模型调用账本" (
    "序号" BIGSERIAL PRIMARY KEY,
    "跟踪号" TEXT NOT NULL DEFAULT '',
    "提供者" TEXT NOT NULL,
    "模型" TEXT NOT NULL,
    "输入Token" INTEGER NOT NULL DEFAULT 0,
    "输出Token" INTEGER NOT NULL DEFAULT 0,
    "花费元" DOUBLE PRECISION NOT NULL DEFAULT 0,
    "创建时间" TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
